language: android
sudo: false
jdk: oraclejdk8
android:
  components:
  - tools
- platform-tools
  - build-tools-23.0.2
  - android-23
  - extra-android-m2repository
before_install:
  - openssl aes-256-cbc -K $encrypted_8343d9b86c86_key -iv $encrypted_8343d9b86c86_iv
    -in keys/cidemo.keystore.enc -out keys/cidemo.keystore -d
  - gem install fir-cli
script:
- cp app/key.properties.example app/key.properties
- keytool -genkey -v -keystore app/debug.keystore -alias AndroidDebugKey -keyalg RSA
  -keysize 2048 -validity 1 -storepass android -keypass android -dname "cn=TEST, ou=TEST,
  o=TEST, c=TE"
- ./gradlew assembleRelease
deploy:
  provider: releases
  api_key:
    secure: XXX
  file: app/build/outputs/apk/app-release.apk
  skip_cleanup: true
  on:
    tags: true
    all_branches: true

after_deploy:
- fir p app/build/outputs/apk/app-release.apk -T $xxxx -c "`git cat-file tag $TRAVIS_TAG`"
- curl -d "appid=11457&to=logan676395@gmail.com&subject=[自动通知] 安卓新版本$TRAVIS_TAG发布&project=u2c0r2&signature=$xxxxxxxx&vars={\"TRAVIS_REPO_SLUG\":\"$TRAVIS_REPO_SLUG\",\"TRAVIS_TAG\":\"$TRAVIS_TAG\",\"TAG_DESCRIPTION\":\"$(git cat-file tag $TRAVIS_TAG | awk 1 ORS='<br>')\"}" https://api.submail.cn/mail/xsend.json
git:
  depth: 1