language: android
sudo: false
jdk: oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - build-tools-23.0.2
  - android-23
  - extra-android-m2repository
before_install:
- openssl aes-256-cbc -K $encrypted_caf26dd8a009_key -iv $encrypted_caf26dd8a009_iv
  -in evandroid.jks.enc -out keys/evandroid.jks -d
- gem install fir-cli
script:
- ./gradlew assembleRelease